// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-uzJ4n6FowtbqCeYbfGtJVmy5sNQNrx4',
    appId: '1:875904455687:web:ccfa2be12f80cc51c3c6a2',
    messagingSenderId: '875904455687',
    projectId: 'task-manager-4ae17',
    authDomain: 'task-manager-4ae17.firebaseapp.com',
    storageBucket: 'task-manager-4ae17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDateD9w0HfKnmHIbub487ohLE-TAAMKx8',
    appId: '1:875904455687:android:e78332c4e1220b47c3c6a2',
    messagingSenderId: '875904455687',
    projectId: 'task-manager-4ae17',
    storageBucket: 'task-manager-4ae17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxBE8PCvm4G9CTmstYDW9okQw5JI8FfKs',
    appId: '1:875904455687:ios:9fede7e3f6f5b861c3c6a2',
    messagingSenderId: '875904455687',
    projectId: 'task-manager-4ae17',
    storageBucket: 'task-manager-4ae17.appspot.com',
    iosBundleId: 'com.example.taskManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxBE8PCvm4G9CTmstYDW9okQw5JI8FfKs',
    appId: '1:875904455687:ios:9fede7e3f6f5b861c3c6a2',
    messagingSenderId: '875904455687',
    projectId: 'task-manager-4ae17',
    storageBucket: 'task-manager-4ae17.appspot.com',
    iosBundleId: 'com.example.taskManagementSystem',
  );
}
